---
apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
  labels:
    name: opensearch-ns
    environment: opensearch-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opens-master
  namespace: opensearch
  labels:
    component: opensearch
    role: master
spec:
  replicas: 3
  selector:
    matchLabels:
      name: opens-master
      component: opensearch
      role: master
  template:
    metadata:
      labels:
        name: opens-master
        component: opensearch
        role: master
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - master
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      hostNetwork: true
      containers:
        - name: opens-master
          image: opensearchproject/opensearch:1.2.0
          env:
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: opensearch_cluster
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
          ports:
            - name: transport
              containerPort: 9600
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-discovery
  namespace: opensearch
  labels:
    component: opensearch
    role: master
spec:
  selector:
    component: opensearch
    role: master
  ports:
    - name: transport
      protocol: TCP
      port: 9600
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opens-data
  namespace: opensearch
  labels:
    component: opensearch
    role: data
spec:
  serviceName: opensearch-data
  replicas: 1
  selector:
    matchLabels:
      name: opens-data
      component: opensearch
      role: data
  template:
    metadata:
      labels:
        name: opens-data
        component: opensearch
        role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - data
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      hostNetwork: true
      containers:
        - name: opens-data
          image: opensearchproject/opensearch:1.2.0
          env:
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: opensearch_cluster
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
          ports:
            - name: transport
              containerPort: 9600
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-data
  namespace: opensearch
  labels:
    component: opensearch
    role: data
spec:
  selector:
    component: opensearch
    role: data
  ports:
    - name: transport
      protocol: TCP
      port: 9600
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opens-client
  namespace: opensearch
  labels:
    component: opensearch
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opens-client
      component: opensearch
      role: client
  template:
    metadata:
      labels:
        name: opens-client
        component: opensearch
        role: client
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - client
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      hostNetwork: true
      containers:
        - name: opens-client-app
          image: opensearchproject/opensearch:1.2.0
          env:
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: opensearch_cluster
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: NETWORK_HOST
              value: _site_,_lo_
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            requests:
              cpu: 1
            limits:
              cpu: 1
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9600
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    component: opensearch
    role: client
spec:
  type: ClusterIP
  selector:
    component: opensearch
    role: client
  ports:
    - name: http
      protocol: TCP
      port: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opens-dashboard
  namespace: opensearch
  labels:
    name: opensearch-dashboard
    app: opensearch-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboard
      name: opensearch-dashboard
  template:
    metadata:
      labels:
        app: opensearch-dashboard
        name: opensearch-dashboard
    spec:
      hostNetwork: true
      containers:
        - name: opensearch-dashboard
          image: opensearchproject/opensearch-dashboards:1.2.0
          env:
            - name: OPENSEARCH_HOSTS
              value: "https://opensearch:9200"
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: opensearch
  labels:
    name: opens-dashboard
    app: dashboard
spec:
  type: ClusterIP
  selector:
    name: opensearch-dashboard
    app: opensearch-dashboard
  ports:
    - name: http
      protocol: TCP
      port: 5701
      targetPort: 5601
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: opens-ingress
  namespace: opensearch
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - secretName: tls-secret
  rules:
    - host: demo.opensearch.lab
      http:
        paths:
          - path: /
            backend:
              serviceName: opensearch
              servicePort: 9200
          - path: /admin
            backend:
              serviceName: dashboard
              servicePort: 5701

